### PR TITLE
Cg-be

### PR DESCRIPTION
**Pull request by thanhnd1503**
merg dev

### CODE REVIEW

**Review by binh113 — APPROVED** [review]
ok

**Review by thienphu2003 — APPROVED** [review]
Phú approve

**Review by consoimauhong — COMMENTED** [review]
thank

**Review by consoimauhong — APPROVED** [review]
thank

**Review by consoimauhong — COMMENTED** [review]
thanks

**Review by consoimauhong — APPROVED** [review]
thanks

**Review by consoimauhong — COMMENTED** [review]
ok

**Pull request merged**
